fix inclusion of adapter in e2e builds

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -224,6 +224,10 @@ jobs:
                   cp -r ./houdini-react/* ./packages/houdini-react/ || echo "Failed to copy houdini-react"
                   rm -rf ./houdini-react
                 fi
+                if [ -d "./adapter-node" ]; then
+                  cp -r ./adapter-node/* ./packages/adapter-node/ || echo "Failed to copy adapter-node"
+                  rm -rf ./adapter-node
+                fi
 
             - name: Create template project
               run: pnpm dlx sv@0.6 create project --types ts --template demo --no-add-ons --no-install
@@ -293,6 +297,10 @@ jobs:
                 if [ -d "./houdini-react" ]; then
                   cp -r ./houdini-react/* ./packages/houdini-react/ || echo "Failed to copy houdini-react"
                   rm -rf ./houdini-react
+                fi
+                if [ -d "./adapter-node" ]; then
+                  cp -r ./adapter-node/* ./packages/adapter-node/ || echo "Failed to copy adapter-node"
+                  rm -rf ./adapter-node
                 fi
 
             - name: Relink workspace dependencies
@@ -388,6 +396,10 @@ jobs:
                   cp -r ./houdini-react/* ./packages/houdini-react/ || echo "Failed to copy houdini-react"
                   rm -rf ./houdini-react
                 fi
+                if [ -d "./adapter-node" ]; then
+                  cp -r ./adapter-node/* ./packages/adapter-node/ || echo "Failed to copy adapter-node"
+                  rm -rf ./adapter-node
+                fi
 
             - name: Relink workspace dependencies
               run: pnpm install
@@ -454,6 +466,10 @@ jobs:
                 if [ -d "./houdini-react" ]; then
                   cp -r ./houdini-react/* ./packages/houdini-react/ || echo "Failed to copy houdini-react"
                   rm -rf ./houdini-react
+                fi
+                if [ -d "./adapter-node" ]; then
+                  cp -r ./adapter-node/* ./packages/adapter-node/ || echo "Failed to copy adapter-node"
+                  rm -rf ./adapter-node
                 fi
 
             - name: Relink workspace dependencies
